version: '3'
services:
  service:
    build: .
    container_name: ack
    hostname: ack
    ports:
      - 3000:3000
    networks:
      - app-network
    volumes:
      - .env:/app/.env
      - .env.share:/app/.env.share
    depends_on:
      - mongodb
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    networks:
      - app-network
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: ack
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped
networks:
  app-network:
    name: app-network
    driver: bridge
volumes:
  mongodb-data:
    driver: local
    