version: '3'
services:
  service:
    build: .
    container_name: ack
    hostname: ack
    ports:
      - 3000:3000
    networks:
      - app-network
    volumes:
      - .env:/app/.env
    depends_on:
      - mongodb
      - zookeeper
      - kafka
    links:
      - mongodb
      - zookeeper
      - kafka
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    networks:
      - app-network
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: ack
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    hostname: zookeeper
    networks:
      - app-network
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/bitnami
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafka
    networks:
      - app-network
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.31.42.2:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_DELETE_TOPIC_ENABLE=false
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ADVERTISED_PORT=9092
    volumes:
      - kafka-data:/bitnami
    depends_on:
      - zookeeper
    links:
      - zookeeper
networks:
  app-network:
    name: app-network
    driver: bridge
volumes:
  mongodb-data:
    driver: local
  zookeeper-data:
    driver: local
  kafka-data:
    driver: local
    