name: ci

on:
  push:
    branches: 
    - main
    - development

jobs:

  run-ci:
    runs-on: ubuntu-latest
    environment: main
    strategy:
      matrix:
        node-version: ['17.3.0']

    services:
      mongodb:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{env.DATABASE_USER}}
          MONGO_INITDB_ROOT_PASSWORD: ${{env.DATABASE_PASSWORD}}
          MONGO_INITDB_DATABASE: ${{env.DATABASE_NAME}}
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup node version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --frozen-lockfile

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_AWS_CREDENTIAL_KEY: ${{ env.AWS_CREDENTIAL_KEY }}
          envkey_AWS_CREDENTIAL_SECRET: ${{ env.AWS_CREDENTIAL_SECRET }}
          envkey_AWS_S3_BUCKET: ${{ env.AWS_S3_BUCKET }}
          envkey_AWS_S3_REGION: ${{ env.AWS_S3_REGION }}
          envkey_DATABASE_NAME: ${{ env.DATABASE_NAME }}
          envkey_DATABASE_PASSWORD: ${{ env.DATABASE_PASSWORD }}
          envkey_DATABASE_USER: ${{ env.DATABASE_USER }}
          envkey_DATABASE_HOST: ${{ env.DATABASE_HOST }}
          directory: ./
          file_name: .env
          fail_on_empty: false

      - name: Migrate
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: migrate
          
      - name: Unit Test
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test

      - name: E2E Test
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test:e2e
