name: ci

on:
  push:
    branches: 
    - main
    - development

jobs:

  run-ci:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        node-version: ['17.3.0']
        mongodb-version: [ '5.0']

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup node version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start mongodb version ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: test-rs
          mongodb-port: 27017

      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --frozen-lockfile
          
      - name: Unit Test
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test

      - name: E2E Test
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test:e2e
