name: ci

on:
  push:
    branches: 
    - main
    - development

jobs:

  run-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Setup node version
        uses: actions/setup-node@v2
        with:
          node-version: '17.3.0'

      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --frozen-lockfile
      - name: Test
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test
