name: ci

on:
  push:
    branches: 
    - main
    - development

jobs:

  run-ci:
    runs-on: ubuntu-latest
    environment: main

    strategy:
      matrix:
        node-version: ['17.x']

    services:
      mongodb:
        image: mongo:latest
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup node version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Install dependencies
        run: yarn migrate
          
      - name: Unit Test
        run: yarn test

      - name: E2E Test
        run: |
          echo "S3 Bucket: $AWS_S3_REGION"
          yarn test:e2e
        env:
          AWS_CREDENTIAL_KEY: ${{ env.AWS_CREDENTIAL_KEY }}
          AWS_CREDENTIAL_SECRET: ${{ env.AWS_CREDENTIAL_SECRET }}
          AWS_S3_BUCKET: ${{ env.AWS_S3_BUCKET }}
          AWS_S3_REGION: ${{ env.AWS_S3_REGION }}
