name: CI
on:
  push:
    branches: 
    - development

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Prepare
        id: prepare
        run: echo "::set-output name=github_short_sha::$(git rev-parse --short HEAD)"

      - name: "Get latest version"
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          exclude_types: "release"
          view_top: 1

      - name: "Print result 1"
        run: |
          echo "id: ${{ steps.last_release.outputs.id }}"
          echo "name: ${{ steps.last_release.outputs.name }}"
          echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"
          echo "created_at: ${{ steps.last_release.outputs.created_atd }}"
          echo "draft: ${{ steps.last_release.outputs.draft }}"
          echo "prerelease: ${{ steps.last_release.outputs.prerelease }}"

      - name: Get latest release of NodeJS
        uses: rez0n/actions-github-release@main
        id: node_release
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "nodejs/node"
          type: "stable"

      - name: "Print result 2"
        run: |
          echo "id: ${{ steps.node_release.outputs.release }}"
          echo "name: ${{ steps.node_release.outputs.release_id }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: docker/setup-buildx-action@v1
        id: builder

      - uses: docker/setup-buildx-action@v1
        id: main

      - name: Builder name
        run: echo ${{ steps.builder.outputs.name }}

      - name: Main builder name
        run: echo ${{ steps.main.outputs.name }}

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build against builder
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder.outputs.name }}
          file: ./prod/dockerfile
          target: builder

      - name: Build against main and push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.main.outputs.name }}
          dockerfile: ./prod/dockerfile
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/ack-nestjs-boilerplate-mongoose
          target: main
          tags: |
            latest
            v${{ steps.last_release.outputs.tag_name }}
            v${{ steps.last_release.outputs.tag_name }}_sha-${{ steps.prepare.outputs.github_short_sha }}
          push: true



