name: ci

on:
  push:
    branches: 
    - main
    - development

jobs:

  run-ci:
    runs-on: ubuntu-latest
    environment: main
    strategy:
      matrix:
        node-version: ['17.3.0']

    services:
      mongo:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{secret.DATABASE_USER}}
          MONGO_INITDB_ROOT_PASSWORD: ${{secret.DATABASE_PASSWORD}}
          MONGO_INITDB_DATABASE: ${{secret.DATABASE_NAME}}
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup node version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --frozen-lockfile
          
      - name: Migrate
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: migrate
          
      - name: Unit Test
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test

      - name: E2E Test
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test:e2e
